### ISSUE TITLE
Add Further Information to Document

### ISSUE THREAD

**Issue by chrisNvalmas** [FullScreenShenanigans/Documentation#41]
Under Initial Setup add:
* That the directory to be used (C:/Code/Shenanigans) has to be made beforehand.

Somewhere  add:
* That FSP can be forked into a different directory and still work

**Comment by JoshuaKGoldberg** [comment]
A note - I think it would make sense to create the directory as part of setup. People will be copy-pasting the samples as is.

**Comment by chrisNvalmas** [comment]
That is true, I noticed the mistake of not making the directory almost right away but it could slip by someone. It's ultimately up to you.
